# Generated by Django 2.0.3 on 2018-03-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0003_transinfo_usetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transinfo',
            name='zh',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
